In [37]:
import agentpy as ap  # Library for creating agents
import numpy as np  # NumPy library for numerical operations
import matplotlib.pyplot as plt  # Library for plotting
import seaborn as sns  # Library for statistical data visualization
from random import randint  # For generating random numbers
import IPython  # For displaying videos in the notebook
from matplotlib.animation import FuncAnimation  # For creating animations (used by agentpy)

In [38]:
class Road(ap.Agent):
    def setup(self):
        self.custom_id = 1 # Custom ID for the road agent
        self.direction_id = None # Direction ID for the road agent to be set within the model
        # 1= southbound, 2= northbound, 3= eastbound, 4= westbound, 5= intersection area
        self.is_spawn = False # Boolean to check if the road agent is a spawn point
        self.is_end = False # Boolean to check if the road agent is an end point

In [67]:
class RoadGeneration(ap.Model):
    def setup(self):
        self.grid = ap.Grid(self, (self.p.dimensions, self.p.dimensions))


        # CREATE ROAD AGENTS
        # Create the intersection matrix
        self.intersection_matrix = self.create_intersection_matrix(self.p.dimensions, self.p.dimensions)
        print(self.intersection_matrix)
    
        # Add road agents to the grid following the intersection matrix, adding each road agent to their respective direction
        # 1= southbound, 2= northbound, 3= eastbound, 4= westbound, 5= intersection area
        for i in range(self.p.dimensions):
            for j in range(self.p.dimensions):
                if self.intersection_matrix[i][j] != 0:
                    #print(i, j, int(self.intersection_matrix[i][j]))
                    road = ap.AgentList(self, 1, Road)
                    road[0].direction_id = int(self.intersection_matrix[i][j])
                    self.grid.add_agents(road, [(int(i), int(j))])
                    
                
    def create_intersection_matrix(self, n, m):
        # Initialize the matrix with zeros
        matrix = np.zeros((n, m))
        
        # Determine the central points
        center_n = n // 2 # center of rows/height
        center_m = m // 2 # center of columns/width
        
        # Adjust for even dimensions - to ensure the intersection is centered
        n_start = center_n - 1 if n % 2 == 0 else center_n
        m_start = center_m - 1 if m % 2 == 0 else center_m
        
        # Create intersection area
        for i in range(n_start, n_start+2):
            for j in range(m_start, m_start+2):
                matrix[i][j] = 5
        
        # Create lanes leading to the intersection
        # Southbound and Northbound lanes
        for i in range(n_start):
            matrix[i][m_start] = 1
            matrix[i][m_start+1] = 2
        for i in range(n_start+2, n):
            matrix[i][m_start] = 1
            matrix[i][m_start+1] = 2
        
        # Eastbound and Westbound lanes
        for j in range(m_start):
            matrix[n_start][j] = 4
            matrix[n_start+1][j] = 3
        for j in range(m_start+2, m):
            matrix[n_start][j] = 4
            matrix[n_start+1][j] = 3
        
        # 1= southbound, 2= northbound, 3= eastbound, 4= westbound, 5= intersection area
        return matrix
        
    def step(self):
        pass

    def update(self):
        pass

    def end(self):
        pass


        



In [68]:
parameters={
    'dimensions': 10,  # Dimensions of the grid
    'steps': 1
}

model = RoadGeneration(parameters)
results = model.run()

#print(model.intersection_agent)


[[0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [4. 4. 4. 4. 5. 5. 4. 4. 4. 4.]
 [3. 3. 3. 3. 5. 5. 3. 3. 3. 3.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]]
Completed: 1 steps
Run time: 0:00:00.007353
Simulation finished


In [69]:
def animation_plot(model, ax):
    attr_grid = model.grid.attr_grid('direction_id')
    color_dict = {1: 'blue', 2: 'red', 3: 'green', 4: 'yellow', 5: 'black', None: 'white'}

    ap.gridplot(attr_grid, ax=ax, color_dict=color_dict, convert=True)

    ax.set_title(f"Road Generation Model\n"
                 f"intersection = black, southbound = blue,\n"
                 f"northbound = red, eastbound = green, westbound = yellow")

fig, ax = plt.subplots()
animation = ap.animate(model, fig, ax, animation_plot)

IPython.display.HTML(animation.to_jshtml(fps=2))

[[0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [4. 4. 4. 4. 5. 5. 4. 4. 4. 4.]
 [3. 3. 3. 3. 5. 5. 3. 3. 3. 3.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 0. 0. 0. 0.]]
